#!/bin/bash

isnum()
{
 if [ -n "$1" ] && [ "$1" -eq "$1" ] 2>/dev/null; then
  return 0
 else
  return 1
 fi
}

exit_()
{
 if [[ -z "$1" ]]; then
  echo "exit_: 0"
  exit 0
 fi
 if ! $(isnum $1); then
  echo -e "${RED}EXIT CODE IS NOT A NUMBER{NC} 1>&2
  return 0
 fi 
 echo "exit_: &1"
 exit $param2
}
